### PR TITLE
Added documentation on repo management.

### PR DESCRIPTION
**Pull request by kommendorkapten**
Rendered version: https://github.com/kommendorkapten/repository-playground/blob/updated-doc/README.md

### CODE REVIEW

**Comment by jku** [comment]
Did you consider updating or replacing [playground/README.md](https://github.com/jku/repository-playground/blob/main/playground/README.md)? It feels like there is overlap... I'm ok with replacing a lot of the README, or moving things don't fit into the already existing IMPLEMENTATION-NOTES.md.

**Comment by kommendorkapten** [comment]
I did not, let me go over that again and freshen up my mind.

**Review by jku — COMMENTED** [review]
This is great. Going forward I'd like to simplify the doc as well (like move the KMS notes to their own doc or within an expandable "details" element) but that is not really required for this PR.

The only question I have is about `playground-status` -- I'm not totally sure why you want to document that: 
* the same data should be visible in the signing event issue comments
* playground-status is part of repository software, not signer tools (so it's not even installed by the dependencies listed here)

It's true that playground-sign isn't super informative right now but that is getting at least partly fixed in #97 ... if we want to give signers more info locally, let's add it there.

**Review by jku — APPROVED** [review]

**Comment by jku** [comment]
I'm pretty sure we can just combine the "operation" and "examples" sections to make this less intimidating with a bit of more work but let's go with this for now. I will open a new issue with ideas for doc improvements

**Pull request merged**
